const FETCH_PEOPLE_ERROR = "It's not your fault, it's ours. There was an error in the People Database.";
const FETCH_UTILITYBILLPROVIDER_ERROR = "It's not your fault, it's ours. There was an error in the Utility Bill Provider Database.";
const FETCH_UTILITYBILL_ERROR = "It's not your fault, it's ours. There was an error in the Utility Bill Database.";
const FETCH_ITEMS_ERROR = "It's not your fault, it's ours. There was an error in the Items Database.";
const FETCH_COMPLAINTS_ERROR = "It's not your fault, it's ours. There was an error in the Items Database.";
const FETCH_CONSUME_ERROR = "It's not your fault, it's ours. There was an error in the Consume Database.";
const FETCH_POSSESSACCOUNTS_ERROR = "It's not your fault, it's ours. There was an error in the Possess Accounts Database.";
const FETCH_DOTASK_ERROR = "It's not your fault, it's ours. There was an error in the Do Task Database.";

const AVAILABLE_PEOPLE_ERROR = "Something went wrong on our end. We couldn't find people who are doings lots of tasks.";
const GET_QUALITY_ITEMS_ERROR = "Sorry, couldn't get what you wanted. An error occurred when we tried getting your results.";
const COMPLAINT_COUNT_ERROR = "Yikes, something happened on our end. It wasn't possible to get the bad roommates! Sorry for the inconvenience.";
const CONSUMED_BY_ALL_ERROR = "Uh oh... An error occurred. We couldn't get you the results.";
const TASK_SELECTION_ERROR = "Sorry, couldn't find the tasks you're looking for. Recheck that you've inputted the correct information.";
const TASK_AGGREGATION_ERROR = "Sorry, couldn't this for you. There was an error when getting the results.";
const DELETE_PERSON_ERROR = "We couldn't remove this person.";
const TASK_INSERT_ERROR = "We couldn't add this new task. Make sure you've added the correct details and you are assigning the task to an existing person!";
const PEOPLE_INSERT_ERROR = "We couldn't add this new person.";
const BILL_PROVIDER_UPDATE_ERROR = "We couldn't update your bill provider. Make sure you have entered the correct bill name or we can't find it!"
const ACCOUNT_UPDATE_ERROR = "We couldn't update your account details. Make sure you have the right account ID."
const TRACK_TRANSACTIONS_ERROR = "We couldn't get you your list of transactions. Perhaps this person has no transactions, or this ID does not exist."

const GENERAL_ERROR = "Something went wrong on our end. Sorry. "

module.exports = {
    FETCH_PEOPLE_ERROR,
    FETCH_UTILITYBILLPROVIDER_ERROR,
    FETCH_UTILITYBILL_ERROR,
    FETCH_ITEMS_ERROR,
    FETCH_COMPLAINTS_ERROR,
    FETCH_CONSUME_ERROR,
    FETCH_POSSESSACCOUNTS_ERROR,
    FETCH_DOTASK_ERROR,
    AVAILABLE_PEOPLE_ERROR,
    GET_QUALITY_ITEMS_ERROR,
    COMPLAINT_COUNT_ERROR,
    CONSUMED_BY_ALL_ERROR,
    TASK_SELECTION_ERROR,
    TASK_AGGREGATION_ERROR,
    DELETE_PERSON_ERROR,
    TASK_INSERT_ERROR,
    PEOPLE_INSERT_ERROR,
    BILL_PROVIDER_UPDATE_ERROR,
    ACCOUNT_UPDATE_ERROR,
    TRACK_TRANSACTIONS_ERROR,
    GENERAL_ERROR
}